language: c
compiler:
        - clang
env:
        - CFLAGS="-std=c99"
os:
        - linux
script:
  - clang -coverage -O0 minunit_example.c -o minunit_example
  - ./minunit_example
  - gcov minunit_example.c
