language: c
compiler:
        - gcc
env:
        - CFLAGS="-fprofile-arcs -ftest-coverage"
os:
        - linux
script:
  - make
  - ./minunit_example
  - gcov minunit_example.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
