language: c
compiler:
        - clang
env:
        - CFLAGS="-std=c11 -coverage -O0"
os:
        - linux
script:
  - make
  - ./minunit_example
  - gcov minunit_example.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
